# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'JavaZone' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JZiOS
  pod 'SwiftyJSON'
  pod 'XCGLogger'
  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'PromiseKit'
  pod 'Realm'
  pod 'RealmSwift'
  pod 'Swinject'
  pod 'ObjectMapper+Realm'
  pod 'Cosmos'
  pod 'AvatarImageView'
  pod 'Toast-Swift'
  pod 'FirebaseCore'
  pod 'FirebaseDatabase'
  pod 'FirebaseFirestore'  # Only iOS and macOS
  pod 'FirebaseFunctions'
  pod 'FirebaseMessaging'  # Only iOS and tvOS
  pod 'FirebaseStorage'
  pod 'Firebase/Analytics'
  pod 'Firebase/RemoteConfig'
  pod 'Fabric'
  pod 'QRCodeReader.swift', '~> 10.0.0'
  pod 'DisplaySwitcher', :git => 'https://github.com/Yalantis/DisplaySwitcher.git'
  pod 'Crashlytics'
  pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
  
  # Uncomment if you use SwinjectStoryboard
  pod 'SwinjectStoryboard'

end
